### ISSUE TITLE
Setup Repository Configuration for Bixi-Api

### ISSUE THREAD

**Issue by k-allagbe** [Monitoring-Mtl/Bixi-Api#1]
Configure essential repository settings.

### Tasks
- [x] Comfigure issue templates for bug reports and feature requests.
- [x] Create `.github/workflows` with CI/CD workflows for testing and deployment.
- [ ] Setup env vars.
- [x] Create a PR template.
- [x] Initial doc
